"""Роли пользователей MKG — связь с агентами ТЗ и agents service user_role."""
from __future__ import annotations

from typing import Any

MKG_ROLES: list[dict[str, Any]] = [
    {
        "id": "admin",
        "name_ru": "Администратор",
        "agent_id": "security",
        "agents_user_role": "admin",
        "can_upload": True,
        "can_extract": True,
        "can_admin": True,
        "can_run_agents": True,
        "description": "Полный доступ, настройки, очистка базы",
        "icon": "⚙️",
        "tagline": "Управление системой и данными",
        "accent_color": "#991b1b",
        "capability_ru": "Настройки пайплайна, RBAC, очистка Neo4j/Qdrant",
        "differs_from": "В отличие от остальных — полные права и destructive-операции",
    },
    {
        "id": "researcher",
        "name_ru": "Исследователь",
        "agent_id": "synthesis",
        "agents_user_role": "researcher",
        "can_upload": True,
        "can_extract": True,
        "can_admin": False,
        "can_run_agents": True,
        "description": "Гипотезы, обзоры литературы, рекомендации",
        "icon": "🔬",
        "tagline": "Гипотезы и связи между фактами",
        "accent_color": "#1e40af",
        "capability_ru": "Режимы «Гипотезы», «Обзор», «Советы» — синтез из графа",
        "differs_from": "Фокус на новых связях и идеях, а не на проверке или пайплайне",
    },
    {
        "id": "engineer",
        "name_ru": "Инженер данных",
        "agent_id": "ingestion",
        "agents_user_role": "engineer",
        "can_upload": True,
        "can_extract": True,
        "can_admin": False,
        "can_run_agents": False,
        "description": "OCR, ingestion, extraction, Neo4j",
        "icon": "🛠",
        "tagline": "Пайплайн: OCR → MD → граф → Neo4j",
        "accent_color": "#166534",
        "capability_ru": "Загрузка, extraction, диагностика ingestion — без LangGraph-агентов",
        "differs_from": "Только инфраструктура данных; не запускает режимы аудита/гипотез",
    },
    {
        "id": "analyst",
        "name_ru": "Аналитик",
        "agent_id": "retrieval",
        "agents_user_role": "analyst",
        "can_upload": False,
        "can_extract": False,
        "can_admin": False,
        "can_run_agents": True,
        "description": "Граф, Qdrant, семантический поиск",
        "icon": "📊",
        "tagline": "Паттерны в графе и Qdrant",
        "accent_color": "#3730a3",
        "capability_ru": "Семантический поиск, сравнение документов, графики из данных MKG",
        "differs_from": "Ищет закономерности в уже загруженных данных, не строит гипотезы",
    },
    {
        "id": "validator",
        "name_ru": "Валидатор",
        "agent_id": "validation",
        "agents_user_role": "validator",
        "can_upload": False,
        "can_extract": False,
        "can_admin": False,
        "can_run_agents": True,
        "description": "Audit mode — противоречия и качество фактов",
        "icon": "✓",
        "tagline": "Проверка фактов и противоречий",
        "accent_color": "#92400e",
        "capability_ru": "Режим «Аудит» — issue / severity / рекомендация",
        "differs_from": "Критикует и проверяет, а не генерирует новые идеи",
    },
    {
        "id": "security",
        "name_ru": "Безопасность",
        "agent_id": "security",
        "agents_user_role": "security",
        "can_upload": False,
        "can_extract": False,
        "can_admin": False,
        "can_run_agents": False,
        "description": "RBAC, грифы, SecurityRole L5",
        "icon": "🔒",
        "tagline": "Грифы и контроль доступа L5",
        "accent_color": "#9d174d",
        "capability_ru": "SecurityRole, классификация, политики RBAC",
        "differs_from": "Фильтрует ответы по уровню допуска, не анализирует содержание",
    },
    {
        "id": "anomaly_hunter",
        "name_ru": "Охотник за аномалиями",
        "agent_id": "retrieval",
        "agents_user_role": "anomaly_hunter",
        "can_upload": False,
        "can_extract": False,
        "can_admin": False,
        "can_run_agents": True,
        "description": "Обход L4-аномалий: HDBSCAN, Neo4j, Qdrant",
        "icon": "🎯",
        "tagline": "Выбросы и странные факты L4",
        "accent_color": "#b45309",
        "capability_ru": "Режим «Аномалии» — обход графа от outlier-узлов",
        "differs_from": "Ищет только аномалии, а не общие паттерны или гипотезы",
    },
    {
        "id": "viewer",
        "name_ru": "Наблюдатель",
        "agent_id": "notification",
        "agents_user_role": "viewer",
        "can_upload": False,
        "can_extract": False,
        "can_admin": False,
        "can_run_agents": False,
        "description": "Только просмотр документов и графа",
        "icon": "👁",
        "tagline": "Read-only: документы и граф",
        "accent_color": "#374151",
        "capability_ru": "Объясняет содержание без изменений данных",
        "differs_from": "Не загружает файлы и не запускает агентов",
    },
]

_ROLES_BY_ID = {r["id"]: r for r in MKG_ROLES}


def get_role(role_id: str) -> dict[str, Any] | None:
    return _ROLES_BY_ID.get(role_id)


def agents_user_role(role_id: str) -> str:
    role = get_role(role_id)
    return str(role["agents_user_role"]) if role else "researcher"
